apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv00001
spec:
  capacity:
    storage: 5Gi
  accessModes:
  - ReadWriteOnce
  nfs:
    path: /var/tmp/nfs/
    server: local
  persistentVolumeReclaimPolicy: Recycle
